@startuml

participant Browser
participant Gear
participant Dodai

Browser -> Gear: POST /v1/question/:question_id/comment (user_credential, question_id, body)
Gear -> Dodai: GET /v1/:appId/:groupId/user/me  (user_credential)
alt user credentialが間違っている
  Gear <-- Dodai: error
  Browser <-- Gear: "error"
else user credentialが正しく、userの取得に成功
  Gear <-- Dodai: user
  Gear -> Dodai: "<font color=blue>GET /v1/:appId/:groupId/Question/:id"
  note right
  指定されたidのQuestionを取得
  end note
  alt 指定されたidのQuestionが存在しない
    Gear <-- Dodai: not found error
    note right
    指定されたidのQuestionが存在しない
    end note
    Browser <-- Gear: not found error
  else
    Gear -> Gear: request bodyをvalidation(bodyが1000文字以下であるかどうかなど)
    alt request bodyの値が不正
      Browser <-- Gear: error
    else
      Gear -> Gear: Questionのcommentsの配列にcommentを追加
      Gear -> Dodai: "<font color=blue>PUT /v1/:appId/:groupId/data/Question"
      note right
      Questionのdocumentを更新
      end note
      Gear <-- Dodai
      Browser <-- Gear
    end
  end
end

@endumlv
